/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import java.io.*;
import java.util.zip.GZIPInputStream;
import java.util.List;
import java.util.ArrayList;
import tools.balok.MemoryAccess;
import tools.balok.MemoryAccessSerializer;
import tools.balok.FrameSerializer;
import balok.ser.SerializedFrame;
import balok.causality.Epoch;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Input;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.ParseException;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;

public class App {
    
    public String getGreeting() {
        return "app should have a greeting";
    }

    public static void main(String[] args) {
        CommandLineParser parser = new DefaultParser();
        Options options = new Options();
        Option time = new Option("t", false, "measure execution time");
        Option silent = new Option("q", false, "do not carry out race detection");
        Option statistics = new Option("c", false, "show statistics of the log file");
        Option parallel = new Option("p", true, "enable parallel data race detection");
        Option sequential = new Option("s", false, "enable sequential data race detection");
        Option localMerge = new Option("m", false, "enable sequential data race detection with local merging optimization");

        options.addOption(time);
        options.addOption(silent);
        options.addOption(statistics);
        options.addOption(parallel);
        options.addOption(sequential);
        options.addOption(localMerge);
        CommandLine line = null;
        HelpFormatter help = new HelpFormatter();
        try {
            line = parser.parse(options, args);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            help.printHelp("java App", options, true);
            System.exit(1);
        }


        // code that handle MemoryAccess objects
        /* ArrayList<MemoryAccess> accesses = new ArrayList<>();
        Kryo kryo = new Kryo();
        kryo.setReferences(false);
        kryo.register(MemoryAccess.class, new MemoryAccessSerializer());
        try {
            Input input = new Input(new GZIPInputStream(new FileInputStream(logFile)));
            MemoryAccess access = null;
            while (!input.eof()) {
                access = kryo.readObject(input, MemoryAccess.class);
                accesses.add(access);
            }
            input.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("Number of memory accesses: " + accesses.size());
        //for (MemoryAccess access: accesses) {
            //System.out.println(access.getAddress() + " " + access.getFile() + " " + access.getLine());
        //}
        MemoryAccessAnalyzer analyzer = new MemoryAccessAnalyzer(accesses);
        analyzer.doRaceDetection(); */


        long start = 0l;
        if (line.hasOption(time.getOpt())) {
            start = System.currentTimeMillis();
        }
        Kryo kryo = new Kryo();
        kryo.setReferences(false);
        kryo.setRegistrationRequired(true);
        kryo.register(SerializedFrame.class, new FrameSerializer());
        long accessNum = 0;
        if (line.getArgs().length == 0) {
            System.out.println("Please input log file");
            help.printHelp("java App", options, true);
            System.exit(1);
        }
        String logFolderName = line.getArgs()[0];
        File logFolder = new File(logFolderName);
        String benchmarkName = logFolderName.substring(logFolderName.lastIndexOf(File.separator) + 1);
        if (!logFolder.isDirectory()) {
            System.out.println(logFolder.getAbsolutePath() + " needs to be a vaild path to the folder containing log files");
            System.exit(1);
        } else if (!logFolder.canRead()) {
            System.out.println(logFolder.getAbsolutePath() + " needs to have read permission");
            System.exit(1);
        }

        FilenameFilter logFileFilter = new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.trim().endsWith(".log") ? true : false;
            }
        };

        ArrayList<Input> logFileInputs = new ArrayList<>();
        try {
            for (File logFile : logFolder.listFiles(logFileFilter)) {
                Input input = new Input(new GZIPInputStream(new FileInputStream(logFile)));
                logFileInputs.add(input);
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

        if (line.hasOption(statistics.getOpt())) {
            // statistics mode
        } else if (line.hasOption(silent.getOpt())) {
            // silent mode
        } else if (line.hasOption(parallel.getOpt())) {
            // parallel data race detection mode
        } else if (line.hasOption(sequential.getOpt())){
            // sequential data race detection mode
        } else if (line.hasOption(localMerge.getOpt())) {
            // sequential data race detection mode with optimizations
        }

        long elapsedTime = 0l;
        if (line.hasOption(time.getOpt())) {
            elapsedTime = System.currentTimeMillis() - start;
            System.out.println("Elapsed Time: " + elapsedTime + " ms");
        }
        System.out.println("Number of memory accesses: " + accessNum);
    }

    private static SerializedFrame<Epoch> getNextFrame(List<Input> inputs) {
        return null;
    }
}
